FROM mcr.microsoft.com/mcas/logcollector
ENV PUBLICIP=log_collector
ENV PROXY=
ENV SYSLOG=true
ENV CONSOLE=<insert_console_address_here>
ENV COLLECTOR=<insert_log_collector_name_here>
CMD (echo <insert_auth_key_here>) | starter
